import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ButtonSelectable from "./components/ButtonSelectable/ButtonSelectable";
import GroupSelectabledButton from "./components/ButtonSelectable/GroupSelectabledButton";
import Labelnput from "./components/Label/Label";
import LabelTextInput from "./components/LabelTextInput/LabelTextInput";
import TipResult from "./components/TipResult/TipResult";
import { Wrapper,SizedBox } from "./styledComponents";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Frontend Mentor | Tip calculator app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav> <Image src='/logo.svg' height={53} width={86} alt='Logo'/> </nav>
      </header>

      <Wrapper>
        <LabelTextInput label='Bill' placeholder='0' />
        <SizedBox/>
        <Labelnput title='Select Tip %'/>
        <GroupSelectabledButton/> 
        <SizedBox/>

        <LabelTextInput label='Number of people' placeholder='0' />
        <TipResult/>
      </Wrapper>
    </div>
  );
}
